const chat = document.getElementById("chat");
const textarea = document.querySelector("textarea");

let lastNotice = "";

/* ADD MESSAGE */
function addMessage(text) {
  const div = document.createElement("div");
  div.className = "msg";
  div.innerText = text;
  chat.appendChild(div);
}

/* ANALYZE */
async function analyze() {
  const input = textarea.value;

  addMessage("👤 " + input);

  try {
    const res = await fetch("http://localhost:3000/analyze", {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({ input })
    });

    const data = await res.json();

    addMessage("🤖 " + data.agent);
    addMessage("👉 " + data.explanation);
    addMessage("⚠️ " + data.notice);
    addMessage("📊 Confidence: " + data.confidence);

    lastNotice = data.notice;

  } catch (err) {
    addMessage("❌ Server error");
  }

  textarea.value = "";
}

/* VOICE */
function startVoice() {
  const SpeechRecognition =
    window.SpeechRecognition || window.webkitSpeechRecognition;

  if (!SpeechRecognition) {
    alert("Use Chrome");
    return;
  }

  const recognition = new SpeechRecognition();
  recognition.lang = "hi-IN";

  recognition.start();

  recognition.onresult = (e) => {
    textarea.value = e.results[0][0].transcript;
    analyze();
  };
}

/* PDF */
function downloadPDF() {
  if (!lastNotice) {
    alert("No notice yet!");
    return;
  }

  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();

  // 🎨 TITLE
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("LEGAL NOTICE", 105, 20, null, null, "center");

  // LINE
  doc.setLineWidth(0.5);
  doc.line(20, 25, 190, 25);

  // 📅 DATE
  const date = new Date().toLocaleDateString();
  doc.setFontSize(10);
  doc.text("Date: " + date, 150, 35);

  // 📄 BODY BOX
  doc.setDrawColor(0);
  doc.rect(15, 45, 180, 200); // box

  // 📝 CONTENT
  doc.setFont("times", "normal");
  doc.setFontSize(12);

  const splitText = doc.splitTextToSize(lastNotice, 160);
  doc.text(splitText, 20, 55);

  // ✍️ SIGNATURE
  doc.setFont("helvetica", "bold");
  doc.text("Signature:", 20, 260);
  doc.line(20, 265, 80, 265);

  // 📌 FOOTER
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(
    "Generated by AI Legal Assistant",
    105,
    285,
    null,
    null,
    "center"
  );

  doc.save("Legal_Notice.pdf");
}
function speakText(text) {
  const speech = new SpeechSynthesisUtterance();

  speech.text = text;
  speech.lang = "hi-IN"; // Hindi + mix
  speech.rate = 1;

  window.speechSynthesis.speak(speech);
}
speakText(data.explanation + ". " + data.notice);
addMessage("👉 " + data.explanation);
addMessage("⚠️ " + data.notice);

// 🔥 AI बोलेगा
speakText(data.explanation + ". " + data.notice);